KinnaryTandel/Skeleton

- ClassLibrary/ClassLibrary.csproj
- ClassLibrary/clsStaff.cs
- Testing3/TestingStaff.csproj
- Testing3/tstStaff.cs
> Added testing for staff class

- ClassLibrary/ClassLibrary.csproj
- ClassLibrary/clsAirline.cs
- Testing4/TestingAirline.csproj
- Testing4/tstAirline.cs
Everything is checked and is ok
> Added testing for the airline class

- ClassLibrary/ClassLibrary.csproj
- ClassLibrary/clsCustomer.cs
- Testing1/TestingCustomer.csproj
- Testing1/tstCustomer.cs
Everything is checked and seems ok
> Added testing for Customer class

- ClassLibrary/clsStaff.cs
- Testing3/tstStaff.cs
Everything was checked and look ok
> Tests Table Customer

- ClassLibrary/clsCustomer.cs
- Testing1/tstCustomer.cs
> Dianas branch

- AdminSystem/CustomerDataEntry.aspx.cs
- AdminSystem/CustomerViewer.aspx.cs
- ClassLibrary/clsCustomer.cs
- Testing1/tstCustomer.cs
and made sure all the tests are… passing
> creating tests for all the attributes 

- AdminSystem/CustomerDataEntry.aspx
- AdminSystem/CustomerDataEntry.aspx.cs
- ClassLibrary/clsCustomer.cs
- Testing1/tstCustomer.cs
(Data and Presentation Layers)
> Creating the Find Method

- ClassLibrary/clsCustomer.cs
- Testing1/tstCustomer.cs
> Adding validation ( Middle Layer )

- AdminSystem/AirlineDataEntry.aspx
- AdminSystem/AirlineDataEntry.aspx.cs
- AdminSystem/AirlineViewer.aspx
- AdminSystem/AirlineViewer.aspx.cs
- AdminSystem/CustomerDataEntry.aspx
- AdminSystem/CustomerDataEntry.aspx.cs
- AdminSystem/CustomerViewer.aspx
- AdminSystem/CustomerViewer.aspx.cs
- AdminSystem/StaffDataEntry.aspx
- AdminSystem/StaffDataEntry.aspx.cs
- AdminSystem/StaffViewer.aspx.cs
- ClassLibrary/clsAirline.cs
- ClassLibrary/clsCustomer.cs
- ClassLibrary/clsStaff.cs
- Skeleton.sln
- Testing1/tstCustomer.cs
- Testing3/tstStaff.cs
- Testing4/tstAirline.cs
Here Is my flight management system testing method
> Flight Management

- AdminSystem/StaffDataEntry.aspx
- AdminSystem/StaffDataEntry.aspx.cs
- ClassLibrary/clsStaff.cs
- Testing3/tstStaff.cs
modifying "OK" button to validated the data.
> display error message on the View for the user.

- AdminSystem/CustomerDataEntry.aspx
- AdminSystem/CustomerDataEntry.aspx.cs
- ClassLibrary/clsCustomer.cs
- Testing1/tstCustomer.cs
> Adding Validation

- AdminSystem/StaffList.aspx
- AdminSystem/StaffList.aspx.cs
- ClassLibrary/ClassLibrary.csproj
- ClassLibrary/clsStaffCollection.cs
- Testing3/TestingStaff.csproj
- Testing3/tstStaffCollection.cs
Displaying the list of name from the database to the web form.
> created clsStaffCollection and test for it.

- AdminSystem/CustomerList.aspx
- AdminSystem/CustomerList.aspx.cs
- ClassLibrary/ClassLibrary.csproj
- ClassLibrary/clsCustomerCollection.cs
- Testing1/TestingCustomer.csproj
- Testing1/tstCustomerCollection.cs
Customer list and count, the Data and presentation Layer
> Created the Collection CLass

- AdminSystem/CustomerDataEntry.aspx.cs
- AdminSystem/CustomerList.aspx
- AdminSystem/CustomerList.aspx.cs
- ClassLibrary/clsCustomerCollection.cs
- Testing1/tstCustomerCollection.cs
Everything checked and works OK
> The Add Method

- AdminSystem/StaffDataEntry.aspx
- AdminSystem/StaffDataEntry.aspx.cs
- AdminSystem/StaffList.aspx
- AdminSystem/StaffList.aspx.cs
- ClassLibrary/clsStaffCollection.cs
- Testing3/tstStaffCollection.cs
made changes to the Data Entry.
> adding the add button.

- ClassLibrary/ClassLibrary.csproj
- ClassLibrary/clsFlight.cs
- Testing2/TestingFlights.csproj
- Testing2/tstFlight.cs
> Flights Test

- AdminSystem/FlightsDataEntry.aspx
- AdminSystem/FlightsDataEntry.aspx.cs
- AdminSystem/FlightsViewer.aspx.cs
- ClassLibrary/clsFlight.cs
- Testing2/tstFlight.cs
> Practical 8 done

- ClassLibrary/clsFlight.cs
- Testing2/tstFlight.cs
> Practical 9a completed

- AdminSystem/StaffLogin.aspx
- AdminSystem/StaffLogin.aspx.cs
- ClassLibrary/ClassLibrary.csproj
- ClassLibrary/clsStaffUser.cs
- Testing3/TestingStaff.csproj
- Testing3/tstStaffUser.cs
> simple login page

- ClassLibrary/clsFlight.cs
- Testing2/tstFlight.cs
> Fix some error from Find test method

- AdminSystem/StaffDataEntry.aspx
- AdminSystem/StaffDataEntry.aspx.cs
- AdminSystem/StaffList.aspx
- AdminSystem/StaffList.aspx.cs
- AdminSystem/StaffLogin.aspx
- AdminSystem/StaffLogin.aspx.cs
- AdminSystem/TeamMainMenu.aspx
- AdminSystem/TeamMainMenu.aspx.cs
made final implements and added main menu.
> Created Main Menu

- AdminSystem/CustomerDataEntry.aspx.cs
- AdminSystem/CustomerList.aspx
- AdminSystem/CustomerList.aspx.cs
- ClassLibrary/clsCustomerCollection.cs
- Testing1/tstCustomerCollection.cs
> Created the Edit Method

- AdminSystem/CustomerConfirmDelete.aspx
- AdminSystem/CustomerConfirmDelete.aspx.cs
- AdminSystem/CustomerList.aspx
- AdminSystem/CustomerList.aspx.cs
- ClassLibrary/clsCustomerCollection.cs
- Testing1/tstCustomerCollection.cs
> Creating the Delete Method

- AdminSystem/CustomerList.aspx
- AdminSystem/CustomerList.aspx.cs
- ClassLibrary/clsCustomerCollection.cs
- Testing1/tstCustomer.cs
- Testing1/tstCustomerCollection.cs
> The filter method

- AdminSystem/CustomerLogin.aspx
- AdminSystem/CustomerLogin.aspx.cs
- AdminSystem/TeamMainMenu.aspx
- ClassLibrary/ClassLibrary.csproj
- ClassLibrary/clsCustomerUser.cs
- Testing1/TestingCustomer.csproj
- Testing1/tstCustomerUser.cs
> Adding a Simple Login Page

- ClassLibrary/clsFlight.cs
- Testing2/tstFlight.cs
> Create test min,max,validation

- AdminSystem/FlightsDataEntry.aspx
- AdminSystem/FlightsDataEntry.aspx.cs
- ClassLibrary/clsFlight.cs
> Practicle 11 complete

- AdminSystem/FlightsDataEntry.aspx.cs
- AdminSystem/FlightsList.aspx
- AdminSystem/FlightsList.aspx.cs
- ClassLibrary/clsFlightCollection.cs
- Testing2/tstFlightCollection.cs
> Practicle 13b done

- AdminSystem/FlightsConfirmDelete.aspx
- AdminSystem/FlightsConfirmDelete.aspx.cs
- AdminSystem/FlightsList.aspx
- AdminSystem/FlightsList.aspx.cs
- ClassLibrary/clsFlightCollection.cs
- Testing2/tstFlightCollection.cs
> Practical 14a complete

- AdminSystem/FlightsList.aspx
- AdminSystem/FlightsList.aspx.cs
- ClassLibrary/clsFlightCollection.cs
- Testing2/tstFlightCollection.cs
> Practical 14b done

- AdminSystem/FlightLogin.aspx
- AdminSystem/FlightLogin.aspx.cs
- ClassLibrary/ClassLibrary.csproj
- ClassLibrary/clsFlightUser.cs
- Testing2/TestingFlights.csproj
- Testing2/tstFlightUser.cs
> Practical 15 done adding login form

- AdminSystem/TeamMainMenu.aspx
- AdminSystem/TeamMainMenu.aspx.cs
> All complete

- AdminSystem/CustomerConfirmDelete.aspx
- AdminSystem/CustomerConfirmDelete.aspx.cs
- AdminSystem/CustomerDataEntry.aspx
- AdminSystem/CustomerDataEntry.aspx.cs
- AdminSystem/CustomerList.aspx
- AdminSystem/CustomerList.aspx.cs
- AdminSystem/CustomerLogin.aspx.cs
- ClassLibrary/clsCustomerCollection.cs
> Implementing the Main Menu

- AdminSystem/StaffConfirmDelete.aspx
- AdminSystem/StaffDataEntry.aspx
- AdminSystem/StaffList.aspx
- AdminSystem/StaffLogin.aspx
- AdminSystem/TeamMainMenu.aspx
making my component look a little better for the user
> added styling to my Staff component
